basePath: /
definitions:
  main.Light:
    properties:
      brightness:
        type: integer
      id:
        type: string
      name:
        type: string
      "on":
        type: boolean
      room:
        type: string
    type: object
  main.LightConcise:
    properties:
      id:
        type: string
      name:
        type: string
      room:
        type: string
    type: object
  main.LightUpdateReq:
    properties:
      brightness:
        type: integer
      name:
        type: string
      "on":
        type: boolean
      room:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for interacting with lighting hub simulator for use in the Josh.ai
    Backend Engineer Coding Challenge.
  title: Josh.ai Coding Challenge API
  version: "1.0"
paths:
  /lights:
    get:
      description: Get list of all lights in the system.
      operationId: get-lights
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.LightConcise'
            type: array
      summary: Get summary of all lights.
    post:
      description: Add a new light to the system.
      operationId: add-light
      parameters:
      - description: Full state of light to add
        in: body
        name: light
        required: true
        schema:
          $ref: '#/definitions/main.Light'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Light'
      summary: Add a light.
  /lights/{lightID}:
    delete:
      description: Remove a light from the system by ID.
      operationId: delete-light-by-id
      parameters:
      - description: ID of light
        in: path
        name: lightID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete a light.
    get:
      description: Get detailed state of a light in the system.
      operationId: get-light-by-id
      parameters:
      - description: ID of light
        in: path
        name: lightID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Light'
      summary: Get details about a light.
    put:
      description: Update the state of a light in the system by ID.
      operationId: update-light-by-id
      parameters:
      - description: ID of light
        in: path
        name: lightID
        required: true
        type: string
      - description: State fields to update
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/main.LightUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Light'
      summary: Update a light.
swagger: "2.0"
